# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c96616262961a21273aea7532b25ba716511c62fc85be9ad7539a2b883ef77c963e72e82e1214d5e1ccdedd7eafefc66de24ba452bda6d40876bb06c7784695c

test:
  secret_key_base: ed49d07438a0673034e5c054651a6bcb500065ef6d4e5a8a40f89ec4e0672f0cb1a3ec42e38dfce4bcfce6c29f6ad808426bab7f137dad17d95c3abfb88736d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
